### ISSUE TITLE
スコアサーバーのteams/:idにおいて、task一覧が時系列順ではなく、task名順になっている問題

### ISSUE THREAD

**Issue by moratorium08** [theoremoon/kosenctfx#25]
masterには当該の処理がなくこのissue内容は、zer0ptsctf2022タグを念頭に置いたものになります。

タイトルに関して、当該の処理では意図としては、「解かれた時間順」に問題を表示するようになっていると思われますが、現状はそのような表示になっていません。

<img width="1194" alt="スクリーンショット 2022-09-04 10 33 42" src="https://user-images.githubusercontent.com/4726469/188293366-5ab612e1-70a0-43dc-a41c-aa6f075df1d8.png">

問題は、 時間のソートのために `solved_at`を参照している点で、 `time` に書き換えることで修正できそうです。

https://github.com/theoremoon/kosenctfx/blob/d2c9c0244031843533f56e8b81eb0382b52ad9c7/ui/pages/teams/%5Bid%5D.tsx#L67-L73

**Comment by theoremoon** [comment]
おお、ずびばぜん… && ありがとうございます
そのうちなおします。CakeCTF2022ではCTF終了後スコアサーバをstatic化するときについでに直しておきます

**Comment by theoremoon** [comment]
何も記憶なないけどこのcommitで直してそうだった https://github.com/theoremoon/kosenctfx/commit/a72c1bcd4e98654b593e443a751459b4bafe4475#diff-fec71b3a38ce0fa8f1d05b8657e477bbdf2ce67e54555e8094362d29e11616c2
